
site_name: Easy Tbot

theme:
    name: material
    feature:
        tabs: true
    palette:
        primary: deep blue
        accent: deep blue

markdown_extensions:
    - pymdownx.highlight
    - pymdownx.superfences
    - admonition

# TODO: Fix navigation
nav:
    - Home: index.md
    # - Quick Start: TODO
    - API:
        easy_tbot: api/easy_tbot.__init__.md
        easy_tbot.core: api/easy_tbot.core.__init__.md
        easy_tbot.core.client: api/easy_tbot.core.client.__init__.md
        easy_tbot.core.client.backend: api/easy_tbot.core.client.backend.md
        easy_tbot.core.client.decorators: api/easy_tbot.core.client.decorators.__init__.md
        easy_tbot.core.client.handlers: api/easy_tbot.core.client.handlers.__init__.md
        easy_tbot.core.cli: api/easy_tbot.core.cli.__init__.md
        easy_tbot.core.cli.backend: api/easy_tbot.core.cli.backend.md
        easy_tbot.core.cli.commads: api/easy_tbot.core.cli.commads.md
        easy_tbot.core.cli.decorator: api/easy_tbot.core.cli.decorator.md
        easy_tbot.core.db: api/easy_tbot.core.db.__init__.md
        easy_tbot.core.db.backend: api/easy_tbot.core.db.backend.md
        easy_tbot.core.template: api/easy_tbot.core.template.__init__.md
        easy_tbot.core.template.backend: api/easy_tbot.core.template.backend.md
        easy_tbot.extra: api/easy_tbot.extra.__init__.md
        easy_tbot.extra.tpl: api/easy_tbot.extra.tpl.__init__.md
        easy_tbot.extra.cli: api/easy_tbot.extra.cli.__init__.md
        easy_tbot.extra.cli.commands: api/easy_tbot.extra.cli.commands.__init__.md
        easy_tbot.extra.create_tbot: api/easy_tbot.extra.create_tbot.md
        easy_tbot.contrib: api/easy_tbot.contrib.__init__.md
        easy_tbot.contrib.client: api/easy_tbot.contrib.client.__init__.md
        easy_tbot.contrib.client.aiogram: api/easy_tbot.contrib.client.aiogram.__init__.md



